CREATE DATABASE IF NOT EXISTS umkm_app CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE umkm_app;

CREATE TABLE umkms (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE aset (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    jenis VARCHAR(100),
    kondisi VARCHAR(50) DEFAULT 'Baik',
    id_umkm INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_umkm) REFERENCES umkms(id) ON DELETE CASCADE
);